### ISSUE TITLE
gulp-browserify doesn't like bespoke-notes plugin

### ISSUE THREAD

**Issue by sokoow** [bespokejs/generator-bespoke#28]
Hey,

I'm just starting using bespoke, and are lame in javascript (<24hrs of experience), but I noticed that there's a slight problem when using gulp-browserify with bespoke-notes:

[20:42:05] Finished 'css' after 1.44 s
[20:42:05] Plumber found unhandled error:
 Error in plugin 'gulp-browserify'
module "./style" not found from "./node_modules/bespoke-notes/index.js"
[20:42:05] Finished 'js' after 1.9 s
[20:42:05] Starting 'build'...

Strange enough, it all works with 'npm start', somebody help please :)

**Comment by hsablonniere** [comment]
Hi @sokoow.

I've done some tests and the problem comes from [medikoo/bespoke-notes](https://github.com/medikoo/bespoke-notes). The README says that if your CJS bundler does not support CSS modules you should do the following :
```
notes = require('bespoke-notes/dom');
```

This triggers code from [this file](https://github.com/medikoo/bespoke-notes/blob/master/dom.js) which does not seem to work properly :

* From what I've understood [here](https://github.com/medikoo/bespoke-notes/blob/master/dom.js#L27), it should be `arguments[1]`
* Maybe there should be a default option for `slideWidth` to prevent [this if](https://github.com/medikoo/bespoke-notes/blob/master/dom.js#L46).

I'm closing the issue since it does not come from the generator. Maybe you should file an issue on [medikoo/bespoke-notes](https://github.com/medikoo/bespoke-notes).
