### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by gleachkr** [bespokejs/generator-bespoke#63]
It may be time to update some of the dependencies the generator brings in. Currently, `npm` throws security warnings as a result of some of the things that `gulp` <4 brings in, and github throws warnings as a result of one of the dependencies (lodash.template) of the now depreciated `gulp-util`.

**Comment by mojavelinux** [comment]
If someone wants to make the switch from Gulp 3 to Gulp 4 (which is no small task) or switch to npm tasks (perhaps a simpler route), I would merge it. I have no intention of updating this project myself as I have moved on to other projects.

**Comment by mojavelinux** [comment]
Thanks to the work by @daveyarwood in the starter project (https://github.com/opendevise/presentation-bespoke-starter/pull/10), I was able to complete this upgrade. The generator itself still uses an old version since it requires a rewrite, but the project it produces is now as update to date as can be expected.
